config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root to: 'welcome#index_gu_laoshi'

  resources :welcome do 
    collection do
      get :index
      get :index_baojiang
      get :index_gu_laoshi
      get :index_fukuan
      get :beijing_waijiao_paiqian
      get :beijing_waijiao_jianzhi_waijiao_paiqian
      get :beijing_waijiao_waidi_quanzhi_waijiao_paiqian
      get :beijing_waijiao_xuexiao_waijiao_faq
      get :geren_waijiao_fuwu_liucheng
      get :geren_waijiao_fuwu_youshi
      get :geren_waijiao_shoufei_qingkuang
      get :geren_waijiao_changjian_wenti

      get :zhujia_waijiao_fuwu_youshi
      get :zhujia_waijiao_fuwu_liucheng
      get :zhujia_waijiao_jiating_xuzhi
      get :zhujia_waijiao_changjian_wenti

      get :waiguo_lietou_fuwu_liucheng
      get :waiguo_lietou_shoufei_qingkuang
      get :contact_us
      get :register
      post :register
    end
  end


  scope :admin, module: 'admin' do 
    scope shallow_path: 'index',  controller: 'index' do
      get  :login
      post :login

      get :registers
      get :show
      get :delete_register
    end
  end  


end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/register.rb
class Register < ApplicationRecord
end

app/controllers/admin/application_controller.rb
class Admin::ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  layout 'admin'
  
  before_action :login_required

  def login_required
    if not session[:logined].present?
      flash[:alert] = '请登录后操作!'     
      redirect_to login_path      
    end
  end

end

app/controllers/admin/index_controller.rb
class Admin::IndexController < Admin::ApplicationController
  skip_before_action :login_required, only: [:login]
    
  
  def login   
    if request.post?      
      if params[:username] == 'admin' and params[:password] == '123456'
        session[:logined] = 'yes'   
        redirect_to registers_path and return   
      end
    end
    render layout: false
  end
  
  def registers
    @registers = Register.all.order('id desc')
  end

  def delete_register
    Register.find(params[:id]).destroy
    redirect_to registers_path
  end

  def show
    @register = Register.find params[:id]
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  skip_before_action :verify_authenticity_token

  def index
    @title = '关于我们'
  end

  def index_gu_laoshi
    @title = '雇一位老师'
  end

  def index_baojiang
    @title = '推荐和评论'
  end

  def index_fukuan  
    @title = '如何付款'  
  end

  def beijing_waijiao_paiqian
    @title = '学校外教-北京全职外教派遣'
  end

  def beijing_waijiao_jianzhi_waijiao_paiqian
    @title = '学校外教-北京兼职外教派遣'
  end

  def beijing_waijiao_waidi_quanzhi_waijiao_paiqian
    @title = '学校外教-外地全职外教派遣'
  end

  def beijing_waijiao_xuexiao_waijiao_faq
    @title = '学校外教-常见问题'
  end

  def geren_waijiao_fuwu_youshi
    @title = '个人外教-服务优势'
  end

  def geren_waijiao_fuwu_liucheng
    @title = '个人外教-服务流程'
  end

  def geren_waijiao_shoufei_qingkuang
    @title = '个人外教-收费情况'
  end

  def geren_waijiao_changjian_wenti
    @title = '个人外教-服务优势'
  end
  
  def zhujia_waijiao_fuwu_youshi
    @title = '住家外教-服务优势'
  end

  def zhujia_waijiao_fuwu_liucheng
    @title = '住家外教-服务流程'
  end

  def zhujia_waijiao_jiating_xuzhi
    @title = '住家外教-家庭须知'
  end

  def zhujia_waijiao_changjian_wenti
    @title = '住家外教-常见问题'
  end

  def waiguo_lietou_fuwu_liucheng
    @title = '外国猎头-服务流程'
  end

  def waiguo_lietou_shoufei_qingkuang
    @title = '外国猎头-收费情况'
  end

  def contact_us
    @title = "联系我们"
  end

  def register
    if request.post?
      params.permit!
      r = Register.new
      r.first_name = params[:first_name]
      r.last_name = params[:last_name]
      r.school_name = params[:school_name]
      r.email = params[:email]
      r.phone = params[:phone]
      r.skype_id = params[:skype_id]
      r.wechat_id = params[:wechat_id]
      r.school_website = params[:school_website]
      r.country_and_city = params[:country_and_city]
      r.teachers_size = params[:teachers_size]
      r.recruitment_needs = params[:recruitment_needs]
      r.question = params[:question]
      r.channel = params[:channel]
      r.save
    end
  end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/index/login.html.slim
<!DOCTYPE html>
html
  head
    title Eagle
    = csrf_meta_tags
    = stylesheet_link_tag    'login', media: 'all', 'data-turbolinks-track': 'reload'     

  body
    .login_panel
      = form_tag login_path, methods: :post do 
        .form-group
          = image_tag 'logostar.png', size: '88x135'
        .form-group
          = text_field_tag 'username', params[:username], class: 'form-control', placeholder: '账号'          
        .form-group
          = text_field_tag 'password', nil, class: 'form-control', type: 'password', placeholder: '密码'

        .form-group
          = submit_tag "登录", class: 'btn btn-transparent'
        - if flash[:alert].present?
          .alert.alert-danger= flash[:alert]          

app/views/admin/index/registers.html.slim
.pd-15
  .panel.panel-default
    .panel-heading    
      i.fa.fa-reorder 
      span.ml-10 申请表

    .panel-body
      .table-responsive
        table.table
          thread
            tr.active
              th 姓名
              th 学校名称
              th 邮箱
              th 电话
              th 申请时间
              th #
          tbody         
            - @registers.each do |r|
              tr
                td #{r.first_name} #{r.last_name}
                td= r.school_name
                td= r.email
                td= r.phone
                td= r.created_at.strftime("%F %T")
                td
                  a.btn.btn-xs.btn-default href="#{show_path(id: r.id)}" 详情
                  a.btn.btn-xs.btn-danger style="margin-left: 10px;" href="#{delete_register_path(id: r.id)}" 删除

app/views/admin/index/show.html.slim
.pd-15
  .panel.panel-default
    .panel-heading    
      i.fa.fa-reorder 
      span.ml-10 详情

    .panel-body
      table.table.table-striped
        tbody
          tr
            td 姓名
            td #{@register.first_name} #{@register.last_name}

          tr
            td 学校名称
            td= @register.school_name

          tr
            td 邮箱
            td= @register.email

          tr
            td 电话
            td= @register.phone        

          tr
            td Skype Id
            td= @register.skype_id

          tr
            td 微信
            td= @register.wechat_id

          tr
            td 学校网站
            td= @register.school_website

          tr
            td 国家/城市
            td= @register.country_and_city

          tr
            td 外教需求数量
            td= @register.teachers_size              

          tr
            td 招聘要求
            td= @register.recruitment_needs

          tr
            td 问题
            td= @register.question

          tr
            td 从哪里了解到我们
            td= @register.channel                                                                  

app/views/layouts/admin.html.slim
<!DOCTYPE html>
html
  head
    title Mandarin Bridge
    meta name="viewport" content="width=device-width, initial-scale=1"
    = csrf_meta_tags
    = stylesheet_link_tag    'admin', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'

  body
    .menu-bar

      ul.nav.nav-pills.nav-stacked
        li
          a href="#{registers_path}"  class="#{params[:action] == 'yijianxiang' ? 'selected' : nil}"
            i.fa.fa-list 
            span.ml-5 申请表      

    .main
      - if true
        .state-nav
          .logo.pull-left
            = image_tag "logostar.png", size: '30x30'
            span.ml-10 北京汉院信息收集平台

      .content
        = yield